modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/vrglab/VrglabsLib/issues"
license = "MIT"

[[mods]]
modId = "vrglabslib"
version = "1.0.0"
displayName = "Vrglabs Lib"
authors = "Vrglab"
description = '''
Architectury based custom data Registration system and Utilities
'''
logoFile = "logo.png"

[[dependencies.vrglabslib]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrglabslib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrglabslib]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
