modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "vrglabslib"
version = "${version}"
displayName = "Vrglabs Lib"
authors = "Vrglab"
description = '''
Better Registration for multi-platform based mods
'''
#logoFile = ""

[[dependencies.vrglabslib]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrglabslib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrglabslib]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
