modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/vrglab/VrglabsLib/issues"
license = "MIT"

[[mods]]
modId = "vrglabslib"
version = "${loader_safe_version}"
displayName = "Vrglabs Lib"
authors = "Vrglab"
description = '''
Architectury based custom data Registration system and Utilities
'''
logoFile = "logo.png"

[[dependencies.vrglabslib]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrglabslib]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrglabslib]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "vrglabslib.mixins.json"
