plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly "curse.maven:shoulder-surfing-reloaded-243190:6993795"

    compileOnly 'javax.servlet:javax.servlet-api:4.0.1'
    implementation 'org.jboss:jboss-vfs:3.3.2.Final'
    implementation 'org.dom4j:dom4j:2.1.4'

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.assertj:assertj-core:4.0.0-M1'
    testImplementation 'org.assertj:assertj-guava:4.0.0-M1'
}

test {
    useJUnitPlatform()
}

sourceSets.main.resources { srcDir 'src/generated/resources' }