plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
    id 'com.diffplug.spotless' version "7.0.0.BETA3"
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common

    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

    compileOnly "curse.maven:shoulder-surfing-reloaded-243190:6993795"

    compileOnly 'javax.servlet:javax.servlet-api:4.0.1'
    implementation 'org.jboss:jboss-vfs:3.3.2.Final'
    implementation 'org.dom4j:dom4j:2.1.4'

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.assertj:assertj-core:4.0.0-M1'
    testImplementation 'org.assertj:assertj-guava:4.0.0-M1'
}

test {
    useJUnitPlatform()
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

