plugins {
    id 'multiloader-loader'
    id 'org.quiltmc.loom' version '1.11.1'
}

repositories {
    maven { url 'https://maven.quiltmc.org/repository/release' }
    maven { url 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }

    modImplementation libs.quilt.loader
    modImplementation libs.bundles.quilted.fabric.api

    compileOnly 'javax.servlet:javax.servlet-api:4.0.1'
    implementation 'org.jboss:jboss-vfs:3.3.2.Final'
    implementation 'org.dom4j:dom4j:2.1.4'

    modApi "com.terraformersmc:modmenu:${modmenu_version}"
    compileOnly "curse.maven:shoulder-surfing-reloaded-243190:6993803"

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.assertj:assertj-core:4.0.0-M1'
    testImplementation 'org.assertj:assertj-guava:4.0.0-M1'
}

test {
    useJUnitPlatform()
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) accessWidenerPath.set(aw)

    mixin { defaultRefmapName.set("${mod_id}.refmap.json") }

    mods {
        // This should match your mod id.
        "vrglabslib" {
            sourceSet("main")
        }
    }

    runs {
        client { client(); setConfigName('Quilt Client'); ideConfigGenerated(true); runDir('runs/client') }
        server { server(); setConfigName('Quilt Server'); ideConfigGenerated(true); runDir('runs/server') }
    }
}