modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "vrglabslib"
version = "1.0.0"
displayName = "Vrglabs Lib"
authors = "Vrglab"
description = '''
Code dependency for all mods to use, make mod making simpler and more dynamic
'''
#logoFile = ""

[[dependencies.vrglabslib]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrglabslib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrglabslib]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
